//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PageantAutostart {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PageantAutostart.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting Button Handle.
        /// </summary>
        internal static string ButtonHandleError {
            get {
                return ResourceManager.GetString("ButtonHandleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageantAutostart v1.0 launched!.
        /// </summary>
        internal static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error launching Pageant.
        /// </summary>
        internal static string PageantLaunchError {
            get {
                return ResourceManager.GetString("PageantLaunchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pageant&apos;s Password Window didn&apos;t appear in Time.
        /// </summary>
        internal static string PageantWindowDidNotAppear {
            get {
                return ResourceManager.GetString("PageantWindowDidNotAppear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error entering Passphrase.
        /// </summary>
        internal static string PassphraseError {
            get {
                return ResourceManager.GetString("PassphraseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting TextBox Handle.
        /// </summary>
        internal static string TextBoxHandleError {
            get {
                return ResourceManager.GetString("TextBoxHandleError", resourceCulture);
            }
        }
    }
}
